# Generated by Django 4.0.8 on 2023-02-27 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0002_rename_bloodgroup_donor_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donor',
            old_name='email',
            new_name='bloodgroup',
        ),
    ]
