# Generated by Django 4.0.8 on 2023-02-28 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0004_remove_donor_bloodgroup_donor_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor',
            name='email',
            field=models.CharField(max_length=40),
        ),
    ]
