# Generated by Django 4.0.8 on 2023-02-28 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0005_alter_donor_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='blooddonate',
            name='weight',
            field=models.CharField(default=10, max_length=10),
            preserve_default=False,
        ),
    ]
