# Generated by Django 4.0.8 on 2023-02-28 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0006_blooddonate_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='blooddonate',
            name='bloodpressure',
            field=models.CharField(default=10, max_length=10),
            preserve_default=False,
        ),
    ]
