# Generated by Django 4.0.8 on 2023-02-28 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0007_blooddonate_bloodpressure'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blooddonate',
            name='bloodpressure',
        ),
    ]
