# Generated by Django 4.0.8 on 2023-02-28 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0009_blooddonate_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='blooddonate',
            name='occupation',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
    ]
