# Generated by Django 4.0.8 on 2023-03-01 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0002_hospitapl_service'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='age',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='bloodgroup',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='disease',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='doctorname',
        ),
        migrations.AddField(
            model_name='patient',
            name='hospital_name',
            field=models.CharField(default=40, max_length=40),
            preserve_default=False,
        ),
    ]
