# Generated by Django 4.0.8 on 2023-03-01 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0003_remove_patient_age_remove_patient_bloodgroup_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='profile_pic',
        ),
    ]
