# Generated by Django 4.0.8 on 2023-03-01 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0004_remove_patient_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='hospital_name',
            field=models.CharField(max_length=30),
        ),
    ]
