# Generated by Django 4.0.8 on 2023-03-04 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital_service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hospital_name', models.CharField(max_length=100)),
                ('hospital_location', models.CharField(max_length=100)),
                ('hospital_start_time', models.TimeField()),
                ('hospital_end_time', models.TimeField()),
                ('hospital_date_donating', models.DateField(blank=True, null=True)),
                ('hospital_phone', models.CharField(default='0788101020', max_length=250)),
                ('post_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': ' Hospital service',
                'ordering': ['-post_date'],
            },
        ),
    ]
