# Generated by Django 4.0.8 on 2023-03-04 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('camps', '0004_hospital_service_hospital_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hospital_service',
            old_name='hospital_end_time',
            new_name='camp_end_time',
        ),
        migrations.RenameField(
            model_name='hospital_service',
            old_name='hospital_location',
            new_name='camp_location',
        ),
        migrations.RenameField(
            model_name='hospital_service',
            old_name='hospital_name',
            new_name='camp_name',
        ),
        migrations.RenameField(
            model_name='hospital_service',
            old_name='hospital_phone',
            new_name='camp_phone',
        ),
        migrations.RenameField(
            model_name='hospital_service',
            old_name='hospital_start_time',
            new_name='camp_start_time',
        ),
    ]
