# Generated by Django 4.0.8 on 2023-03-04 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('camps', '0013_remove_hospital_service_camp_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hospital_service',
            old_name='camp_end_time',
            new_name='hospital_end_time',
        ),
        migrations.RenameField(
            model_name='hospital_service',
            old_name='camp_location',
            new_name='hospital_location',
        ),
        migrations.RenameField(
            model_name='hospital_service',
            old_name='camp_name',
            new_name='hospital_name',
        ),
        migrations.RenameField(
            model_name='hospital_service',
            old_name='camp_phone',
            new_name='hospital_phone',
        ),
        migrations.RenameField(
            model_name='hospital_service',
            old_name='camp_start_time',
            new_name='hospital_start_time',
        ),
    ]
