# Generated by Django 4.0.8 on 2023-03-04 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camps', '0014_rename_camp_end_time_hospital_service_hospital_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital_service',
            name='hospital_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
