# Generated by Django 4.0.8 on 2023-03-04 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camps', '0015_hospital_service_hospital_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital_service',
            name='hospital_date',
            field=models.DateField(),
        ),
    ]
