# Generated by Django 4.0.8 on 2023-03-04 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('camps', '0018_alter_hospital_service_hospital_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hospital_service',
            name='hospital_date',
        ),
    ]
